const products=[
{id:'oud-marakja',name:'OUD MARAKUJA',price:2400,img:'oud-marakoka.jpg',desc:'A rich, warm oud fragrance with a smooth fruity edge. Bold, elegant and made for evening wear.',notes:'Oud • Fruity • Warm'},
{id:'oud-for-great',name:'OUD FOR GREAT',price:2400,img:'oud-for-greatness.jpg',desc:'A confident oud blend with a deep, refined character. A statement scent for those who like to stand out.',notes:'Oud • Woody • Amber'},
{id:'oud-supreme',name:'OUD SUPREME',price:2100,img:'oud-supreme.jpg',desc:'Deep and luxurious with a polished woody feel. Designed to leave a memorable trail without feeling heavy.',notes:'Oud • Woody • Rich'},
{id:'sabaya',name:'SABAYA',price:1700,img:'oud-marakoka.jpg',desc:'A graceful everyday scent with a soft, inviting character. Easy to wear from daytime plans to evening outings.',notes:'Floral • Soft • Elegant'},
{id:'hugo-boss',name:'HUGO BOSS',price:2000,img:'hugo-boss.jpg',desc:'Clean, confident and effortlessly modern. A versatile fragrance for a sharp everyday impression.',notes:'Fresh • Woody • Modern'},
{id:'creed-aventus',name:'CREED AVENTUS',price:2200,img:'oud-for-greatness.jpg',desc:'A bold, sophisticated profile with a fresh opening and a powerful masculine character. Made for confidence.',notes:'Fresh • Fruity • Woody'},
{id:'gucci-flora',name:'GUCCI FLORA',price:1600,img:'vanilla.jpg',desc:'Soft, feminine and graceful, with a charming floral mood that feels polished and easy to wear.',notes:'Floral • Sweet • Elegant'},
{id:'vanilla',name:'VANILLA',price:1400,img:'vanilla.jpg',desc:'A creamy, comforting vanilla fragrance with a sweet and cozy character. Perfect when you want something inviting.',notes:'Vanilla • Sweet • Warm'},
{id:'jadore',name:"J'ADORE",price:1500,img:'hugo-boss.jpg',desc:'An elegant floral-inspired fragrance with a soft, luxurious mood. Feminine, graceful and timeless.',notes:'Floral • Soft • Elegant'},
{id:'dunhill-desire',name:'DUNHILL DESIRE',price:1700,img:'oud-supreme.jpg',desc:'Warm, confident and distinctive. A strong everyday-to-evening fragrance for a polished finish.',notes:'Warm • Woody • Spicy'},
{id:'euphoria',name:'EUPHORIA',price:1500,img:'vanilla.jpg',desc:'A smooth, alluring scent with a warm and sensual feel. Ideal for evenings and special moments.',notes:'Warm • Floral • Sensual'}
];
const money=n=>'PKR '+n.toLocaleString('en-PK');
let bag=JSON.parse(localStorage.getItem('veloraBag')||'[]');
function save(){localStorage.setItem('veloraBag',JSON.stringify(bag));updateBag()}
function updateBag(){document.querySelectorAll('[data-count]').forEach(x=>x.textContent=bag.length);let box=document.getElementById('cartItems');if(!box)return;box.innerHTML=bag.length?bag.map((p,i)=>`<div class="cart-item"><img src="assets/${p.img}"><div><b>${p.name}</b><small>${money(p.price)}</small><button onclick="removeItem(${i})">Remove</button></div></div>`).join(''):'<p class="muted">Your bag is empty.</p>';let t=bag.reduce((a,p)=>a+p.price,0);let el=document.getElementById('cartTotal');if(el)el.textContent=money(t)}
function add(id){let p=products.find(x=>x.id===id);if(p){bag.push(p);save();toast('Added to your bag');openCart()}}
function removeItem(i){bag.splice(i,1);save()}
function openCart(){document.getElementById('cart')?.classList.add('open');document.getElementById('shade')?.classList.add('show');updateBag()}
function closeCart(){document.getElementById('cart')?.classList.remove('open');document.getElementById('shade')?.classList.remove('show')}
function orderOne(id){let p=products.find(x=>x.id===id);if(!p)return;let msg=`Hi VELORA! I want to order:\n\nProduct: ${p.name}\nPrice: ${money(p.price)}\n\nName:\nPhone:\nCity:\nComplete address:`;window.open('https://wa.me/923120590220?text='+encodeURIComponent(msg),'_blank')}
function orderCart(){if(!bag.length){toast('Your bag is empty');return}let lines=bag.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n');let total=bag.reduce((a,p)=>a+p.price,0);let msg=`Hi VELORA! I want to place an order.\n\n${lines}\n\nTotal: ${money(total)}\n\nName:\nPhone:\nCity:\nComplete address:`;window.open('https://wa.me/923120590220?text='+encodeURIComponent(msg),'_blank')}
function toast(s){let x=document.getElementById('toast');if(!x)return;x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function card(p){return `<article class="card"><a href="product.html?id=${p.id}" class="pic"><img src="assets/${p.img}" alt="${p.name}"></a><div class="cardbody"><span>${p.notes}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="cardfoot"><b>${money(p.price)}</b><button onclick="add('${p.id}')">Add to bag</button></div></div></article>`}
function renderProducts(list=products){let g=document.getElementById('productGrid');if(g)g.innerHTML=list.map(card).join('')}
function initProducts(){let q=(document.getElementById('search')?.value||'').toLowerCase();renderProducts(products.filter(p=>p.name.toLowerCase().includes(q)||p.notes.toLowerCase().includes(q)))}
function initDetail(){let id=new URLSearchParams(location.search).get('id');let p=products.find(x=>x.id===id)||products[0];let root=document.getElementById('detail');if(!root)return;root.innerHTML=`<div class="detailphoto"><img src="assets/${p.img}" alt="${p.name}"></div><div class="detailcopy"><span class="eyebrow">VELORA PERFUME</span><h1>${p.name}</h1><div class="pricebig">${money(p.price)}</div><p>${p.desc}</p><div class="notes"><b>Fragrance profile</b><span>${p.notes}</span></div><p class="delivery">✓ Cash on Delivery available<br>✓ Order directly on WhatsApp<br>✓ Carefully packed for delivery</p><div class="detailbuttons"><button class="primary" onclick="orderOne('${p.id}')">ORDER NOW →</button><button class="secondary" onclick="add('${p.id}')">ADD TO BAG</button></div><a class="back" href="products.html">← Back to all perfumes</a></div>`}
document.addEventListener('DOMContentLoaded',()=>{updateBag();renderProducts();initProducts();initDetail();document.getElementById('search')?.addEventListener('input',initProducts)});
