const products = [
  {id:'oud-marakauja', name:'Oud Marakuja', price:2400, image:'assets/oud-marakoka.jpg', desc:'A bold, warm fragrance with a polished oud character and a modern fruity edge. Made for confident evenings and memorable first impressions.', mood:'Bold · Warm · Modern', detail:'Oud Marakuja brings a rich, expressive mood that feels dressed-up without being heavy. A strong choice when you want your fragrance to stand out.'},
  {id:'oud-for-great', name:'Oud For Great', price:2400, image:'assets/oud-for-greatness.jpg', desc:'Deep, confident and elegant — a statement fragrance for evenings, occasions and moments that deserve extra presence.', mood:'Rich · Confident · Elegant', detail:'A commanding oud-inspired profile with a refined character. Wear it when you want a sophisticated, noticeable finish.'},
  {id:'oud-supreme', name:'Oud Supreme', price:2100, image:'assets/oud-supreme.jpg', desc:'Smooth, deep and sophisticated, with the kind of presence that works beautifully for dressed-up days and nights out.', mood:'Smooth · Deep · Sophisticated', detail:'Oud Supreme is built around a strong, refined fragrance mood. It is an easy pick for formal occasions and evening wear.'},
  {id:'sabaya', name:'Sabaya', price:1700, image:'assets/oud-marakoka.jpg', desc:'A graceful everyday scent with a soft, polished character. Easy to wear, easy to remember and made for effortless confidence.', mood:'Graceful · Soft · Everyday', detail:'Sabaya keeps things elegant and approachable. A versatile choice for daily wear when you want a clean, put-together fragrance.'},
  {id:'hugo-boss', name:'Hugo Boss', price:2000, image:'assets/hugo-boss.jpg', desc:'Fresh, clean and effortlessly confident in character — a versatile choice for work, casual days and evenings.', mood:'Fresh · Clean · Versatile', detail:'Hugo Boss is presented as an easy-to-wear fragrance option with a confident, modern feel that fits a wide range of occasions.'},
  {id:'creed-aventus', name:'Creed Aventus', price:2200, image:'assets/hugo-boss.jpg', desc:'A confident, premium-feeling fragrance profile designed for people who like a strong and polished signature.', mood:'Premium · Strong · Refined', detail:'Creed Aventus is a statement-style fragrance with a polished presence. Ideal when you want a scent that feels confident and distinctive.'},
  {id:'gucci-flora', name:'Gucci Flora', price:1600, image:'assets/vanilla.jpg', desc:'Soft, feminine and graceful, with an elegant mood that suits daytime plans, gatherings and special moments.', mood:'Floral · Graceful · Feminine', detail:'Gucci Flora brings a softer, elegant mood to the collection. A lovely option when you want your fragrance to feel light and refined.'},
  {id:'vanilla', name:'Vanilla', price:1400, image:'assets/vanilla.jpg', desc:'Sweet, creamy and comforting with a warm vanilla mood. An easy everyday fragrance with a cozy finish.', mood:'Sweet · Creamy · Cozy', detail:'Vanilla is the easy comfort pick — warm, inviting and simple to wear whenever you want a softer fragrance mood.'},
  {id:'jadore', name:"J'adore", price:1500, image:'assets/oud-for-greatness.jpg', desc:'Elegant and feminine in mood, designed for a polished presence that feels right from daytime plans to evenings out.', mood:'Elegant · Feminine · Polished', detail:"J'adore adds a graceful, dressed-up feel to the collection. Choose it for occasions where you want something elegant and memorable."},
  {id:'dunhill-desire', name:'Dunhill Desire', price:1700, image:'assets/hugo-boss.jpg', desc:'Warm, confident and masculine in mood, with a versatile character for everyday wear and evening plans.', mood:'Warm · Masculine · Versatile', detail:'Dunhill Desire is a confident everyday option with a warm, polished mood that transitions easily from day to night.'},
  {id:'euphoria', name:'Euphoria', price:1500, image:'assets/oud-supreme.jpg', desc:'Smooth, expressive and slightly mysterious — a fragrance choice for evenings, gatherings and standout moments.', mood:'Expressive · Smooth · Mysterious', detail:'Euphoria brings a more atmospheric feel to the collection. A good choice when you want your fragrance to have a little extra character.'}
];
const WHATSAPP_NUMBER='923120590220';
let bag=[];
function money(n){return 'Rs. '+Number(n).toLocaleString('en-PK')}
function getProduct(id){return products.find(p=>p.id===id)}
function productCard(p){return `<article class="product"><a class="pic" href="product.html?id=${encodeURIComponent(p.id)}"><img src="${p.image}" alt="${p.name} perfume" loading="lazy"><span class="view-pill">View product →</span></a><div class="info"><div class="tag">PERFUME</div><h3><a href="product.html?id=${encodeURIComponent(p.id)}">${p.name}</a></h3><p>${p.desc}</p><div class="row"><span class="price">${money(p.price)}</span><button class="add" onclick='add(${JSON.stringify(p.name)})'>Add +</button><button class="order" onclick='orderProduct(${JSON.stringify(p.name)})'>Order</button></div></div></article>`}
function render(){const grid=document.getElementById('grid');if(!grid)return;const q=(document.getElementById('search')?.value||'').toLowerCase();const list=products.filter(p=>!q||p.name.toLowerCase().includes(q)||p.desc.toLowerCase().includes(q));grid.innerHTML=list.map(productCard).join('')||"<p class='empty'>No fragrance found. Try another name.</p>"}
function add(name){const p=products.find(x=>x.name===name);if(!p)return;bag.push(p);update();toast('Added to your bag ✦')}
function remove(i){bag.splice(i,1);update()}
function update(){const c=document.getElementById('count'),items=document.getElementById('items'),total=document.getElementById('total');if(c)c.textContent=bag.length;if(items)items.innerHTML=bag.length?bag.map((p,i)=>`<div class="item"><span>${p.name}<br><small>${money(p.price)}</small></span><button onclick="remove(${i})">Remove</button></div>`).join(''):'<p class="empty">Your bag is empty.</p>';if(total)total.textContent=money(bag.reduce((a,p)=>a+p.price,0))}
function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('shade').classList.add('show')}
function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('shade').classList.remove('show')}
function orderProduct(name){const p=products.find(x=>x.name===name);if(!p)return;const msg=`Hi VELORA! I want to order this perfume.\n\nPerfume: ${p.name}\nPrice: ${money(p.price)}\n\nName:\nPhone:\nCity:\nComplete address:`;window.open('https://wa.me/'+WHATSAPP_NUMBER+'?text='+encodeURIComponent(msg),'_blank')}
function checkout(){if(!bag.length){toast('Add a perfume first');return}const lines=bag.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n');const total=bag.reduce((a,p)=>a+p.price,0);const msg=`Hi VELORA! I want to place an order.\n\n${lines}\n\nTotal: ${money(total)}\n\nName:\nPhone:\nCity:\nComplete address:`;window.open('https://wa.me/'+WHATSAPP_NUMBER+'?text='+encodeURIComponent(msg),'_blank')}
function focusSearch(){const s=document.getElementById('search');if(s){document.querySelector('.products-section')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>s.focus(),350)}else window.location.href='products.html'}
function renderProductPage(){const root=document.getElementById('product-detail');if(!root)return;const id=new URLSearchParams(location.search).get('id');const p=getProduct(id)||products[0];document.title=`VELORA — ${p.name}`;root.innerHTML=`<div class="detail-media"><img src="${p.image}" alt="${p.name} perfume"></div><div class="detail-copy"><div class="eyebrow">VELORA · PERFUME</div><h1>${p.name}</h1><div class="detail-price">${money(p.price)}</div><p class="detail-lead">${p.desc}</p><div class="detail-line"></div><div class="detail-meta"><div><span>MOOD</span><b>${p.mood}</b></div><div><span>ORDER</span><b>Cash on delivery</b></div></div><p class="detail-text">${p.detail}</p><button class="btn detail-order" onclick='orderProduct(${JSON.stringify(p.name)})'>Order now <span>→</span></button><button class="detail-add" onclick='add(${JSON.stringify(p.name)})'>Add to bag</button><a class="back-link" href="products.html">← Back to perfumes</a></div>`}
let t;function toast(s){const x=document.getElementById('toast');if(!x)return;x.textContent=s;x.classList.add('showtoast');clearTimeout(t);t=setTimeout(()=>x.classList.remove('showtoast'),1800)}
render();renderProductPage();update();
